### ISSUE TITLE
Docker apt repos no longer exist

### ISSUE THREAD

**Issue by directhex** [dotnet/dotnet-buildtools-prereqs-docker#280]
> Notice: Shutting down dockerproject.org APT and YUM repos 2020-03-31
Docker will be shutting down the deprecated APT and YUM repositories hosted at "dockerproject.org" and "dockerproject.com" on the 31st of March 2020.

> We noticed that this project is referencing one of these repositories, and recommend updating to use the "download.docker.com" repository to prevent disruption.

> More info: https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/

e.g. https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages

This breaks all image building which uses these repos, as of right now, e.g. https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/581676/logs/194

**Comment by akoeplinger** [comment]
@mthalman this seems to be coming from the underlying VM the Azure Pipelines agent is running on rather than some script in this repo.

**Comment by mthalman** [comment]
This should be resolved now by the changes that had been made in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/279.  That's because the Linux build agents that have this issue of not using the correct package feed are no longer attempting to run `apt-get update`.

**Comment by MichaelSimons** [comment]
@mthalman - Shouldn't the agents still get fixed so that this doesn't present further problems down the road?  Can you follow up with DDFUN?
